TEST: True
MODEL_NUM: 900

##----------------- ENV Parameters ------------------------------
EXP_NAME: DDPG_GSP_Neighbors_Gate_9
ARGOS_FILE_NAME: collectiveRlTransport_bash.argos
NUM_EPISODES: 100
NUM_OBSTACLES: 0
USE_GATE: 1
GATE_MIN: 4
GATE_CURRICULUM: 0
NUM_ROBOTS: 4
MAX_NUM_ROBOT_FAILURES: 0
CHANCE_FAILURE: 0.25
PORT: 55560
SEED: 124

##----------------- Object Parameters ----------------------------
USE_PRISMS: 0
RANDOM_OBJECTS: 0
TEST_PRISM: 0

##----------------- Actor Parameters -----------------------------
LEARNING_SCHEME: DDPG
OPTIONS_PER_ACTION: 3
MIN_MAX_ACTION: 1.0
META_PARAM_SIZE: 1
PROX_FILTER_ANGLE_DEG: 60.0

##----------------- GSP Parameters --------------------------------
GLOBAL_KNOWLEDGE: False
GSP: True
RECURRENT: False
ATTENTION: False
NEIGHBORS: True
GSP_INPUT_SIZE: 4
GSP_OUTPUT_SIZE: 1
GSP_MIN_MAX_ACTION: 1.0
GSP_LOOK_BACK: 2
GSP_SEQUENCE_LENGTH: 5
RECURRENT_HIDDEN_SIZE: 256
RECURRENT_EMBEDDING_SIZE: 256
RECURRENT_NUM_LAYERS: 5

##----------------- Hyper Parameters -----------------------------
# Learning Rates
GAMMA: 0.99997
TAU: 0.005
ALPHA: 0.001
BETA: 0.002
LR: 0.0001

# Epsilon Greedy
EPSILON: 1.0
EPS_MIN: 0.01
EPS_DEC: 0.00005

# ACTOR
BATCH_SIZE: 64
MEM_SIZE: 100000
REPLACE_TARGET_COUNTER: 1000
NOISE: 0.1
UPDATE_ACTOR_ITER: 2
WARMUP: 1000

# GSP
GSP_LEARNING_FREQUENCY: 500
GSP_BATCH_SIZE: 128
